# Config file for automatic testing at travis-ci.com

language: python
python:
  - 3.9
#  - 3.8
#  - 3.7
#  - 3.6
  - 3.5

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:  #pip install -U tox-travis
  - pip3 install -r requirements.txt

# Command to run tests, e.g. python setup.py test
script: pytest -v #tox

# Assuming you have installed the travis-ci CLI tool, after you
# create the Github repo and add it to Travis, run the
# following command to finish PyPI deployment setup:
# $ travis encrypt --add deploy.password
#deploy:
#  provider: pypi
#  distributions: sdist bdist_wheel
#  user: raalesir
#  password:
#    secure: PLEASE_REPLACE_ME
#  on:
#    tags: true
#    repo: raalesir/distributed_trajectories
#    python: 3.8
